# Generated by Django 5.1.2 on 2024-12-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
