# Generated by Django 5.1.2 on 2025-06-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sub1', models.FloatField()),
                ('sub2', models.FloatField()),
            ],
        ),
    ]
