# Generated by Django 5.1.2 on 2025-03-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sub1', models.CharField(max_length=100)),
                ('sub2', models.CharField(max_length=100)),
            ],
        ),
    ]
