# Generated by Django 5.1.2 on 2025-02-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
    ]
