# Generated by Django 5.1.2 on 2025-01-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sub1', models.IntegerField()),
                ('sub2', models.IntegerField()),
            ],
        ),
    ]
